import type { MetadataRoute } from "next";

const base = (process.env.NEXT_PUBLIC_SITE_URL || "https://suedeai.ai").replace(/\/$/, "");
const lastModified = new Date("2026-04-30T00:00:00.000Z");
const iosLastModified = new Date("2026-05-18T00:00:00.000Z");

const jasonColapietroImages = [
  "jason-colapietro-suede-ai-founder-portrait.png",
  "jason-colapietro-suede-ai-you-build-different-real.png",
  "jason-colapietro-suede-ai-wave-underneath.png",
  "jason-colapietro-suede-ai-it-compounds.png",
  "jason-colapietro-suede-ai-game-day-energy.png",
  "jason-colapietro-suede-ai-built-the-road.png",
  "jason-colapietro-suede-ai-flip-the-model.png",
  "jason-colapietro-suede-ai-creators-paid-nothing.png",
  "jason-colapietro-suede-ai-builders-question-everything.png",
  "jason-colapietro-suede-ai-voice-get-paid.png",
  "jason-colapietro-suede-ai-building-for-family.png",
  "jason-colapietro-suede-ai-reach-further.png",
  "jason-colapietro-suede-ai-voice-infrastructure.png",
  "jason-colapietro-suede-ai-stakes-personal.png",
  "jason-colapietro-suede-ai-infrastructure-weekends.png",
  "jason-colapietro-suede-ai-everything-gets-clearer.png",
  "jason-colapietro-suede-ai-ledger-registered-first.png",
  "jason-colapietro-suede-ai-programmable-ownership.png",
  "jason-colapietro-suede-ai-now-it-exists-story.png",
  "jason-colapietro-suede-ai-get-in-the-water.png",
  "jason-colapietro-suede-ai-she-needs-you-there.png",
  "jason-colapietro-suede-ai-what-all-of-it-is-for.png",
  "jason-colapietro-suede-ai-long-game.png",
  "jason-colapietro-suede-ai-presence-is-product.png",
  "jason-colapietro-suede-ai-mission-and-moment.png",
  "jason-colapietro-suede-ai-invert-the-model.png",
  "jason-colapietro-suede-ai-nothing-obvious.png",
  "jason-colapietro-suede-ai-show-up-get-in.png",
  "jason-colapietro-suede-ai-day-off-building-infrastructure.png",
  "jason-colapietro-suede-ai-simple-reason.png",
  "jason-colapietro-suede-ai-family-outdoor.png",
  "jason-colapietro-suede-ai-reading-candid.png",
  "jason-colapietro-suede-ai-close-reading.png",
  "jason-colapietro-suede-ai-shoulder-ride.png",
  "jason-colapietro-suede-ai-sunglasses-smile.png",
  "jason-colapietro-suede-ai-sunny-candid.png",
  "jason-colapietro-suede-ai-table-candid.png",
  "jason-colapietro-suede-ai-family-event.png",
  "jason-colapietro-suede-ai-desk-shot.png",
  "jason-colapietro-suede-ai-collage.png",
  "jason-colapietro-suede-ai-night-out.png",
  "jason-colapietro-suede-ai-painting-date.png",
  "jason-colapietro-suede-ai-painting-action.png",
  "jason-colapietro-suede-ai-two-person-smile.png",
  "jason-colapietro-suede-ai-birthday-cake.png",
  "jason-colapietro-suede-ai-birthday-cake-full.png",
  "jason-colapietro-suede-ai-fun-closeup.png",
  "jason-colapietro-suede-ai-seated-polo.png",
  "jason-colapietro-suede-ai-black-jacket-close.png",
  "jason-colapietro-suede-ai-black-jacket-seated.png",
  "jason-colapietro-suede-ai-profile-signal.png",
  "jason-colapietro-suede-ai-profile-standard.png",
  "jason-colapietro-suede-ai-profile-sharp.png",
  "jason-colapietro-suede-ai-profile-current.png",
  "jason-colapietro-suede-ai-profile-built-in.png",
  "jason-colapietro-suede-ai-profile-proof.png",
  "jason-colapietro-suede-ai-profile-waterline.png",
  "jason-colapietro-suede-ai-profile-ready.png",
  "jason-colapietro-suede-ai-profile-origin.png",
  "jason-colapietro-suede-ai-profile-ownership.png",
  "jason-colapietro-suede-ai-profile-composure.png",
  "jason-colapietro-suede-ai-profile-early.png",
  "jason-colapietro-suede-ai-profile-angle.png",
  "jason-colapietro-suede-ai-profile-focus.png",
  "jason-colapietro-suede-ai-profile-archive.png",
  "jason-colapietro-suede-ai-profile-frame.png",
  "jason-colapietro-suede-ai-profile-resolve.png",
  "jason-colapietro-suede-ai-profile-long-view.png",
  "jason-colapietro-suede-ai-profile-signal-stack.png",
  "jason-colapietro-suede-ai-profile-name-on-it.png",
].map((file) => `${base}/jason-colapietro/${file}`);

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: base,
      lastModified,
      changeFrequency: "weekly",
      priority: 1,
    },
    {
      url: `${base}/founder`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: `${base}/ios`,
      lastModified: iosLastModified,
      changeFrequency: "weekly",
      priority: 0.95,
    },
    {
      url: `${base}/crypto-investing-ai-ip-rwa-music`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.9,
    },
    {
      url: `${base}/jason-colapietro-images`,
      lastModified,
      changeFrequency: "monthly",
      priority: 0.9,
      images: jasonColapietroImages,
    },
  ];
}
